# This workflow assembles all Yara rules into a single file

name: Assemble Yara

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - name: Check-out the repository
        uses: actions/checkout@v2

      # Assemble all *.yar files (except those requiring external variables)
      - name: Assemble all Yara files
        run: |
          excluded_rules=(
            "generic_anomalies.yar"
            "general_cloaking.yar"
            "gen_webshells_ext_vars.yar"
            "thor_inverse_matches.yar"
            "yara_mixed_ext_vars.yar"
            "configured_vulns_ext_vars.yar"
            "gen_fake_amsi_dll.yar"
            "expl_citrix_netscaler_adc_exploitation_cve_2023_3519.yar"
            "expl_connectwise_screenconnect_vuln_feb24.yar"
            "gen_mal_3cx_compromise_mar23.yar"
            "gen_susp_obfuscation.yar"
            "gen_vcruntime140_dll_sideloading.yar"
            "yara-rules_vuln_drivers_strict_renamed.yar"
          )

          for f in "$GITHUB_WORKSPACE"/yara/*.yar; do
            skip_rule=false

            for excluded_rule in "${excluded_rules[@]}"; do
              if [[ "${f##*/}" == "${excluded_rule}" ]]; then
                skip_rule=true
                break
              fi
            done

            if [[ "${skip_rule}" == false ]]; then
              cat "$f" >> signature-base.yar
            fi
          done

      # Upload the assembled Yara artifact
      - name: Upload the resulting Yara artifact
        uses: actions/upload-artifact@v4
        with:
          name: signature-base.yar
          path: signature-base.yar
